if (ANDROID_NDK)
  SET(GENERATOR_KEY android)
elseif (MINGW)
  SET(GENERATOR_KEY mingw)
elseif (MSVC)
  SET(GENERATOR_KEY msvc)
elseif (IOS)
  SET(GENERATOR_KEY ios)
else ()
  message(FATAL_ERROR "Unsupported Generator.")
endif ()
