if (ANDROID_NDK)
  SET(GENERATOR_KEY android)
elseif (MINGW)
  SET(GENERATOR_KEY mingw)
elseif (MSVC)
  SET(GENERATOR_KEY msvc)
elseif (IOS)
  SET(GENERATOR_KEY ios)
  elseif (UNIX) # Caution: this also seems to be set to true on Mac.
    SET(GENERATOR_KEY linux)
else ()
  message(FATAL_ERROR "Unsupported Generator.")
endif ()
